-----------------------CREACI?N DE LAS TABLAS----------------------

--DROP TABLE MEMBERS;


CREATE TABLE MEMBERS (
ID_MEMBER VARCHAR2(5) CONSTRAINT PK_ID_MEMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(20),
ID_NUMBER VARCHAR2(12) UNIQUE,
PASS_NAME VARCHAR2(20) UNIQUE,
PHONE_NUMBER VARCHAR2(12),
EMAIL_ADDRESS VARCHAR2(50),
ADDRESS VARCHAR2(50)
);

--DROP TABLE CLASSES;


CREATE TABLE CLASSES (
ID_CLASS VARCHAR2(5) CONSTRAINT PK_ID_CLASS PRIMARY KEY,
CLASS_NAME VARCHAR2(20),
EXERCISE_TYPE VARCHAR2(20),
INSTRUCTOR VARCHAR2(20),
CLASSROOM VARCHAR2(12), 
DATE_TIME DATE
);

--DROP TABLE RESERVE;


CREATE TABLE RESERVE (
ID_MEMBER VARCHAR2(5) CONSTRAINT FK_ID_MEMBER_MEMBERS REFERENCES MEMBERS(ID_MEMBER),
ID_CLASS VARCHAR2(5) CONSTRAINT FK_ID_CLASS_CLASSES REFERENCES CLASSES(ID_CLASS)
);


---------------PLAN DE CONTINGENCIA BORRADO TABLAS------------------------

--DROP TABLE RESERVE
--CASCADE CONSTRAINTS;

--DROP TABLE CLASSES
--CASCADE CONSTRAINTS;

--DROP TABLE MEMBERS
--CASCADE CONSTRAINTS;
