--------------------INSERCION DATOS TABLA MEMBERS-------------------

SET SERVEROUTPUT ON;

BEGIN

    INSERT INTO MEMBERS (ID_MEMBER, FIRST_NAME, LAST_NAME,ID_NUMBER, PASS_NAME, PHONE_NUMBER, EMAIL_ADDRESS, ADDRESS) 
    VALUES ('MEM1', 'Darth', 'Vader', '00000001x', '666999666', '2509J', 'darthvader@gmail.com', 'Death Star Square 1');
    
    INSERT INTO MEMBERS (ID_MEMBER, FIRST_NAME, LAST_NAME,ID_NUMBER, PASS_NAME, PHONE_NUMBER, EMAIL_ADDRESS, ADDRESS) 
    VALUES ('MEM2', 'Rocket', 'Racoon', '33333334y', '777888999', '3986P', 'rocketracoon@gmail.com', 'Knowhere 55');
    
    INSERT INTO MEMBERS (ID_MEMBER, FIRST_NAME, LAST_NAME,ID_NUMBER, PASS_NAME, PHONE_NUMBER, EMAIL_ADDRESS, ADDRESS) 
    VALUES ('MEM3', 'Harry', 'Potter', '99999999z','456987123', 'HP23', 'harrypotter@hotmail.com', 'Privet Drive St 9');
    
    INSERT INTO MEMBERS (ID_MEMBER, FIRST_NAME, LAST_NAME,ID_NUMBER, PASS_NAME, PHONE_NUMBER, EMAIL_ADDRESS, ADDRESS) 
    VALUES ('MEM4', 'Pikachu', 'First Generation', '4758691a', 'PI07', '777111333', 'superpikachu@gmail.com', 'Pokeball Square 001');
    
    INSERT INTO MEMBERS (ID_MEMBER, FIRST_NAME, LAST_NAME,ID_NUMBER, PASS_NAME, PHONE_NUMBER, EMAIL_ADDRESS, ADDRESS) 
    VALUES ('MEM5', 'James', 'Bond', '00000007x', '000000777', '3006', 'bondjames@gmx.es', 'Agitado Club 7');
    
    INSERT INTO MEMBERS (ID_MEMBER, FIRST_NAME, LAST_NAME,ID_NUMBER, PASS_NAME, PHONE_NUMBER, EMAIL_ADDRESS, ADDRESS) 
    VALUES ('MEM6', 'Austin', 'Powers', '98765432x', '777444123', 'AP69', 'powersaustin@gmail.com', 'Happy Flowers St 3');
    
    INSERT INTO MEMBERS (ID_MEMBER, FIRST_NAME, LAST_NAME,ID_NUMBER, PASS_NAME, PHONE_NUMBER, EMAIL_ADDRESS, ADDRESS) 
    VALUES ('MEM7', 'Bob', 'Sponge', '66632145t', '994458767', 'BS78', 'Spongebob@gmail.com', 'Pineapple under the sea St 1');
    
    COMMIT;


EXCEPTION

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
DBMS_OUTPUT.PUT_LINE('SE ELIMINAN LOS INSERTS');

ROLLBACK;
END;

-------------INSERCIÓN DATOS TABLA RESERVE------------

BEGIN

INSERT INTO RESERVE (ID_MEMBER, ID_CLASS) VALUES ('MEM3','CL7');
INSERT INTO RESERVE (ID_MEMBER, ID_CLASS) VALUES ('MEM2','CL5');
INSERT INTO RESERVE (ID_MEMBER, ID_CLASS) VALUES ('MEM7','CL5');
INSERT INTO RESERVE (ID_MEMBER, ID_CLASS) VALUES ('MEM1','CL1');
INSERT INTO RESERVE (ID_MEMBER, ID_CLASS) VALUES ('MEM4','CL3');

COMMIT;

EXCEPTION

WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('SE ELIMINAN LOS INSERTS');
    
    ROLLBACK;


END;



