----------------------------PARAMETRIZACI?N INICIAL------------------------------------------
--INSERCI?N DATOS TABLA CLASSES--

SET SERVEROUTPUT ON;

BEGIN
    INSERT INTO CLASSES (ID_CLASS, CLASS_NAME, EXERCISE_TYPE, INSTRUCTOR, CLASSROOM, DATE_TIME) 
    VALUES ('CL1', 'Spinning', 'Cardio', 'Elom Musk', 'Sala 1', TO_DATE('22/05/2023 12:00:00PM', 'DD/MM/YYYY HH:MI:SSPM'));
    
    INSERT INTO CLASSES (ID_CLASS, CLASS_NAME, EXERCISE_TYPE, INSTRUCTOR, CLASSROOM, DATE_TIME) 
    VALUES ('CL2', 'Bodypump', 'Cardio', 'Bill Gates', 'SALA 3', TO_DATE('25/05/2023 03:00:00PM', 'DD/MM/YYYY HH:MI:SSPM'));
    
    INSERT INTO CLASSES (ID_CLASS, CLASS_NAME, EXERCISE_TYPE, INSTRUCTOR, CLASSROOM, DATE_TIME) 
    VALUES ('CL3', 'TRX', 'Power', 'Jeff Bezos', 'SALA 2', TO_DATE('27/05/2023 08:00:00PM', 'DD/MM/YYYY HH:MI:SSPM'));
    
    INSERT INTO CLASSES (ID_CLASS, CLASS_NAME, EXERCISE_TYPE, INSTRUCTOR, CLASSROOM, DATE_TIME) 
    VALUES ('CL5', 'Pilates', 'Stretching', 'Amancio Ortega', 'SALA 2', TO_DATE('23/05/2023 03:00:00PM', 'DD/MM/YYYY HH:MI:SSPM'));
    
    INSERT INTO CLASSES (ID_CLASS, CLASS_NAME, EXERCISE_TYPE, INSTRUCTOR, CLASSROOM, DATE_TIME) 
    VALUES ('CL6', 'Body Combat', 'Cardio', 'Juan Roig', 'SALA 9', TO_DATE('26/05/2023 09:00:00PM', 'DD/MM/YYYY HH:MI:SSPM'));
    
    INSERT INTO CLASSES (ID_CLASS, CLASS_NAME, EXERCISE_TYPE, INSTRUCTOR, CLASSROOM, DATE_TIME) 
    VALUES ('CL7', 'Zumba', 'Cardio', 'Patricia Botin', 'SALA 10', TO_DATE('27/05/2023 01:00:00PM', 'DD/MM/YYYY HH:MI:SSPM'));
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('SE ELIMINAN LOS INSERTS');
    ROLLBACK;


END;

--COMPROBAMOS LA CORRECTA INSERCI?N DE REGISTROS
--SELECT * FROM CLASSES;

