SET SERVEROUTPUT ON;

BEGIN
    DELETE FROM RESERVE WHERE ID_MEMBER='MEM1';
    DELETE FROM RESERVE WHERE ID_MEMBER='MEM2';
    DELETE FROM RESERVE WHERE ID_MEMBER='MEM3';
    DELETE FROM RESERVE WHERE ID_MEMBER='MEM4';
    DELETE FROM RESERVE WHERE ID_MEMBER='MEM7';
    
COMMIT;

EXCEPTION

    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('SE DESHACE LA ELIMINACI?N DE REGISTROS');
    
ROLLBACK;

END;


BEGIN
    DELETE FROM CLASSES WHERE ID_CLASS='CL1';
    DELETE FROM CLASSES WHERE ID_CLASS='CL2';
    DELETE FROM CLASSES WHERE ID_CLASS='CL3';
    DELETE FROM CLASSES WHERE ID_CLASS='CL5';
    DELETE FROM CLASSES WHERE ID_CLASS='CL6';
    DELETE FROM CLASSES WHERE ID_CLASS='CL7';
    
COMMIT;

EXCEPTION

    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('SE DESHACE LA ELIMINACI?N DE REGISTROS');

ROLLBACK;

END;

BEGIN

    DELETE FROM MEMBERS WHERE ID_MEMBER='MEM1';
    DELETE FROM MEMBERS WHERE ID_MEMBER='MEM2';
    DELETE FROM MEMBERS WHERE ID_MEMBER='MEM3';
    DELETE FROM MEMBERS WHERE ID_MEMBER='MEM4';
    DELETE FROM MEMBERS WHERE ID_MEMBER='MEM6';
    
COMMIT;
    

EXCEPTION

    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('SE DESHACE LA ELIMINACI?N DE REGISTROS');
    
ROLLBACK;

END;